// Parallel Planner with Review — four-phase orchestration loop
//
// This template drives a multi-phase workflow:
//   Phase 1 (Plan):             An opus agent analyzes open issues, builds a
//                               dependency graph, and outputs a <plan> JSON
//                               listing unblocked issues with branch names.
//   Phase 2 (Execute + Review): For each issue, a sandbox is created via
//                               createSandbox(). The implementer runs first
//                               (100 iterations). If it produces commits or
//                               the branch already has commits ahead of the
//                               merge base, a reviewer runs in the same
//                               sandbox on the same branch (1 iteration).
//                               All issue pipelines run concurrently via
//                               Promise.allSettled().
//   Phase 3 (Merge):            A single agent merges all completed branches
//                               into the current branch.
//
// The outer loop repeats up to MAX_ITERATIONS times so that newly unblocked
// issues are picked up after each round of merges.
//
// Usage:
//   npm run sandcastle
// Or directly: tsx .sandcastle/main.mts

import { exec, execFile } from "node:child_process";
import { promisify } from "node:util";
import * as sandcastle from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";

const execAsync = promisify(exec);
const execFileAsync = promisify(execFile);

type PlannedIssue = { id: string; title: string; branch: string };

const LIST_TASKS_COMMAND = `{{LIST_TASKS_COMMAND}}`;

async function listReadyIssuesJson(): Promise<string> {
  const { stdout } = await execAsync(LIST_TASKS_COMMAND, {
    maxBuffer: 10 * 1024 * 1024,
  });
  return stdout.trim() || "[]";
}

function extractAllowedIssueIds(issuesJson: string): Set<string> {
  const parsed = JSON.parse(issuesJson) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error("Ready issue list did not contain a JSON array.");
  }

  return new Set(
    parsed
      .map((issue) => {
        if (!issue || typeof issue !== "object") return undefined;
        const record = issue as { id?: unknown; number?: unknown };
        const id = record.id ?? record.number;
        return id === undefined || id === null ? undefined : String(id);
      })
      .filter((id): id is string => id !== undefined),
  );
}

function assertPlanUsesAllowedIssues(
  issues: PlannedIssue[],
  allowedIssueIds: Set<string>,
): void {
  const outOfScope = issues.filter(
    (issue) => !allowedIssueIds.has(String(issue.id)),
  );
  if (outOfScope.length > 0) {
    throw new Error(
      `Planner selected issue(s) outside this run's ready queue: ${outOfScope
        .map((issue) => issue.id)
        .join(", ")}`,
    );
  }
}

/** Host repo branch that issue branches merge into (current HEAD). */
async function getCurrentBranch(): Promise<string> {
  const { stdout } = await execFileAsync("git", [
    "rev-parse",
    "--abbrev-ref",
    "HEAD",
  ]);
  return stdout.trim();
}

/** Commits on `branch` not reachable from `baseRef` (pending merge work). */
async function countBranchCommitsAhead(
  baseRef: string,
  branch: string,
): Promise<number> {
  try {
    const { stdout } = await execFileAsync("git", [
      "rev-list",
      `${baseRef}..refs/heads/${branch}`,
      "--count",
    ]);
    const count = parseInt(stdout.trim(), 10);
    return Number.isNaN(count) ? 0 : count;
  } catch {
    return 0;
  }
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// Maximum number of plan→execute→merge cycles before stopping.
// Raise this if your backlog is large; lower it for a quick smoke-test run.
const MAX_ITERATIONS = 10;

// Stop scheduling an issue after this many consecutive implement runs with
// zero new commits (prevents burning iterations on orphan branches).
const EMPTY_RUN_CIRCUIT_BREAKER_THRESHOLD = 3;

// Hooks run inside the sandbox before the agent starts each iteration.
// bootstrap.sh defines repository-specific setup (generated by init).
const hooks = {
  sandbox: {
    onSandboxReady: [
      {
        command: "bash .sandcastle/bootstrap.sh",
        timeoutMs: 300_000,
      },
    ],
  },
};

const sandboxProvider = docker({
  mounts: [],
});

// ---------------------------------------------------------------------------
// Main loop
// ---------------------------------------------------------------------------

/** Consecutive implement runs with zero new commits, keyed by issue id. */
const consecutiveEmptyImplementRuns = new Map<string, number>();

function excludeCircuitBrokenIssues(issues: PlannedIssue[]): PlannedIssue[] {
  const active: PlannedIssue[] = [];

  for (const issue of issues) {
    const streak = consecutiveEmptyImplementRuns.get(issue.id) ?? 0;
    if (streak >= EMPTY_RUN_CIRCUIT_BREAKER_THRESHOLD) {
      console.warn(
        `  ${issue.id}: skipped — ${streak} consecutive implement runs produced no new commits.`,
      );
      console.warn(
        `    Actions: merge branch ${issue.branch}, close issue ${issue.id}, or fix the merge gate.`,
      );
      continue;
    }
    active.push(issue);
  }

  return active;
}

function recordImplementRunOutcome(
  issueId: string,
  commitsThisRun: number,
  branchCommitsAhead: number,
  currentBranch: string,
): void {
  const branchHasUnmergedWork = branchCommitsAhead > 0;

  if (commitsThisRun === 0) {
    const streak = (consecutiveEmptyImplementRuns.get(issueId) ?? 0) + 1;
    consecutiveEmptyImplementRuns.set(issueId, streak);
    if (branchHasUnmergedWork) {
      console.log(
        `  ${issueId}: no new commits this run; branch has ${branchCommitsAhead} commit(s) ahead of ${currentBranch} — eligible for review/merge`,
      );
    } else {
      console.log(`  ${issueId}: no work on branch; nothing to merge.`);
    }
    return;
  }

  consecutiveEmptyImplementRuns.set(issueId, 0);
}

for (let iteration = 1; iteration <= MAX_ITERATIONS; iteration++) {
  console.log(`\n=== Iteration ${iteration}/${MAX_ITERATIONS} ===\n`);

  // -------------------------------------------------------------------------
  // Phase 1: Plan
  //
  // The planning agent (opus, for deeper reasoning) reads the open issue list,
  // builds a dependency graph, and selects the issues that can be worked in
  // parallel right now (i.e., no blocking dependencies on other open issues).
  //
  // It outputs a <plan> JSON block — we parse that to drive Phase 2.
  // -------------------------------------------------------------------------
  const readyIssuesJson = await listReadyIssuesJson();
  const allowedIssueIds = extractAllowedIssueIds(readyIssuesJson);

  const plan = await sandcastle.run({
    hooks,
    sandbox: sandboxProvider,
    name: "planner",
    // One iteration is enough: the planner just needs to read and reason,
    // not write code.
    maxIterations: 1,
    // Opus for planning: dependency analysis benefits from deeper reasoning.
    agent: sandcastle.claudeCode("claude-opus-4-6"),
    promptFile: "./.sandcastle/plan-prompt.md",
    promptArgs: {
      ISSUES_JSON: readyIssuesJson,
    },
  });

  // Extract the <plan>…</plan> block from the agent's stdout.
  const planMatch = plan.stdout.match(/<plan>([\s\S]*?)<\/plan>/);
  if (!planMatch) {
    throw new Error(
      "Planning agent did not produce a <plan> tag.\n\n" + plan.stdout,
    );
  }

  // The plan JSON contains an array of issues, each with id, title, branch.
  const { issues } = JSON.parse(planMatch[1]!) as {
    issues: PlannedIssue[];
  };
  assertPlanUsesAllowedIssues(issues, allowedIssueIds);

  if (issues.length === 0) {
    // No unblocked work — either everything is done or everything is blocked.
    console.log("No unblocked issues to work on. Exiting.");
    break;
  }

  const activeIssues = excludeCircuitBrokenIssues(issues);

  if (activeIssues.length === 0) {
    console.log(
      "All planned issues hit the empty-run circuit breaker. Exiting.",
    );
    break;
  }

  console.log(
    `Planning complete. ${activeIssues.length} issue(s) to work in parallel:`,
  );
  for (const issue of activeIssues) {
    console.log(`  ${issue.id}: ${issue.title} → ${issue.branch}`);
  }

  // -------------------------------------------------------------------------
  // Phase 2: Execute + Review
  //
  // For each issue, create a sandbox via createSandbox() so the implementer
  // and reviewer share the same sandbox instance per branch. The implementer
  // runs first; if it produces commits or the branch already has unmerged
  // work, the reviewer runs in the same sandbox.
  //
  // Promise.allSettled means one failing pipeline doesn't cancel the others.
  // -------------------------------------------------------------------------

  const currentBranch = await getCurrentBranch();

  const settled = await Promise.allSettled(
    activeIssues.map(async (issue) => {
      const sandbox = await sandcastle.createSandbox({
        branch: issue.branch,
        sandbox: sandboxProvider,
        hooks,
      });

      try {
        // Check the LOCAL issue branch first. If it already has commits ahead
        // of the base (e.g. a prior iteration implemented it but review/merge
        // never finished), skip a fresh implementer run and go straight to
        // review/merge. This uses local refs only, so it never matches an
        // unrelated same-numbered branch from another remote.
        const priorCommitsAhead = await countBranchCommitsAhead(
          currentBranch,
          issue.branch,
        );

        let implement: Awaited<ReturnType<typeof sandbox.run>> | undefined;
        if (priorCommitsAhead > 0) {
          console.log(
            `  ${issue.id}: branch already has ${priorCommitsAhead} commit(s) ahead of ${currentBranch}; skipping fresh implementation.`,
          );
        } else {
          implement = await sandbox.run({
            name: "implementer",
            maxIterations: 100,
            agent: sandcastle.claudeCode("claude-sonnet-4-6"),
            promptFile: "./.sandcastle/implement-prompt.md",
            promptArgs: {
              TASK_ID: issue.id,
              ISSUE_TITLE: issue.title,
              BRANCH: issue.branch,
            },
          });
        }

        const commitsThisRun = implement?.commits.length ?? 0;
        const branchCommitsAhead = await countBranchCommitsAhead(
          currentBranch,
          issue.branch,
        );
        const branchHasUnmergedWork = branchCommitsAhead > 0;
        const shouldReview = commitsThisRun > 0 || branchHasUnmergedWork;

        recordImplementRunOutcome(
          issue.id,
          commitsThisRun,
          branchCommitsAhead,
          currentBranch,
        );

        let pipelineResult = implement;
        if (shouldReview) {
          const review = await sandbox.run({
            name: "reviewer",
            maxIterations: 1,
            agent: sandcastle.claudeCode("claude-sonnet-4-6"),
            promptFile: "./.sandcastle/review-prompt.md",
            promptArgs: {
              BRANCH: issue.branch,
            },
          });

          // Merge commits from both runs so the merge phase sees all of them.
          // Each sandbox.run() only returns commits from its own run.
          pipelineResult = {
            ...review,
            commits: [...(implement?.commits ?? []), ...review.commits],
          };
        }

        return { ...pipelineResult!, branchHasUnmergedWork };
      } finally {
        await sandbox.close();
      }
    }),
  );

  // Log any agents that threw (network error, sandbox crash, etc.).
  for (const [i, outcome] of settled.entries()) {
    if (outcome.status === "rejected") {
      console.error(
        `  ✗ ${activeIssues[i]!.id} (${activeIssues[i]!.branch}) failed: ${outcome.reason}`,
      );
    }
  }

  // Include branches that produced commits this cycle or already have unmerged
  // work on their issue branch (e.g. a prior run failed review before merge).
  const completedIssues = settled
    .map((outcome, i) => ({ outcome, issue: activeIssues[i]! }))
    .filter(
      (entry) =>
        entry.outcome.status === "fulfilled" &&
        (entry.outcome.value.commits.length > 0 ||
          entry.outcome.value.branchHasUnmergedWork),
    )
    .map((entry) => entry.issue);

  const completedBranches = completedIssues.map((i) => i.branch);

  console.log(
    `\nExecution complete. ${completedBranches.length} branch(es) eligible for merge:`,
  );
  for (const branch of completedBranches) {
    console.log(`  ${branch}`);
  }

  if (completedBranches.length === 0) {
    console.log("No branches with unmerged work. Nothing to merge.");
    continue;
  }

  // -------------------------------------------------------------------------
  // Phase 3: Merge
  //
  // One agent merges all completed branches into the current branch,
  // resolving any conflicts and running tests to confirm everything works.
  //
  // The {{BRANCHES}} and {{ISSUES}} prompt arguments are lists that the agent
  // uses to know which branches to merge and which issues to close.
  // -------------------------------------------------------------------------
  await sandcastle.run({
    hooks,
    sandbox: sandboxProvider,
    name: "merger",
    maxIterations: 1,
    agent: sandcastle.claudeCode("claude-sonnet-4-6"),
    promptFile: "./.sandcastle/merge-prompt.md",
    promptArgs: {
      // A markdown list of branch names, one per line.
      BRANCHES: completedBranches.map((b) => `- ${b}`).join("\n"),
      // A markdown list of issue IDs and titles, one per line.
      ISSUES: completedIssues.map((i) => `- ${i.id}: ${i.title}`).join("\n"),
    },
  });

  console.log("\nBranches merged.");
}

console.log("\nAll done.");
