import {
  appendHubTaskComment,
  loadHubTaskBoard,
  type HubTaskProjection,
  type HubTaskStatus,
} from "./taskBoard.js";
import { execFileSync } from "node:child_process";
import { TaskBoardError } from "./errors.js";

export const HUB_TRIAGE_COMMENT_PREFIX =
  "> *This was generated by AI during triage.*";

export type HubTriageOutcome =
  | "needs_info"
  | "ready_for_agent"
  | "ready_for_human"
  | "wontfix";

export const HUB_TRIAGE_SOURCE_STATUSES = ["inbox", "needs_info"] as const;

const HUB_TRIAGE_SOURCE_STATUS_SET = new Set<string>(
  HUB_TRIAGE_SOURCE_STATUSES,
);

const OUTCOME_LABELS: Readonly<Record<HubTriageOutcome, string>> = {
  needs_info: "needs-info",
  ready_for_agent: "ready-for-agent",
  ready_for_human: "ready-for-human",
  wontfix: "wontfix",
};

const TRIAGE_LABELS_TO_CLEAR = [
  "needs-triage",
  "needs-info",
  "ready-for-agent",
  "ready-for-human",
] as const;

const MIN_SPECIFIED_DESCRIPTION_LENGTH = 24;

export interface HubTriageDecision {
  readonly outcome: HubTriageOutcome;
  readonly summary: string;
}

export interface TriageHubTaskRecord {
  readonly taskId: string;
  readonly priorStatus: HubTaskStatus;
  readonly outcome: HubTriageOutcome;
}

export interface TriageHubTasksResult {
  readonly triaged: readonly TriageHubTaskRecord[];
  readonly skipped: readonly {
    readonly taskId: string;
    readonly reason: string;
  }[];
}

export interface TriageHubTasksInput {
  readonly cwd: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly classify?: (task: HubTaskProjection) => HubTriageDecision;
}

const runBdText = (
  cwd: string,
  args: readonly string[],
  failureLabel: string,
  env: NodeJS.ProcessEnv = process.env,
): string => {
  try {
    return execFileSync("bd", [...args], {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env,
    });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "unable to execute bd";
    throw new TaskBoardError({
      message: `sandcastle ${failureLabel} requires Beads in the current repo: ${message}`,
    });
  }
};

export const isHubTriageComment = (body: string | undefined): boolean =>
  (body ?? "").trimStart().startsWith(HUB_TRIAGE_COMMENT_PREFIX);

export const formatHubTriageComment = (summary: string): string =>
  `${HUB_TRIAGE_COMMENT_PREFIX}\n\n${summary.trim()}`;

const taskText = (task: HubTaskProjection): string =>
  [task.title, task.description, task.notes].filter(Boolean).join("\n");

const hasSufficientSpecification = (task: HubTaskProjection): boolean =>
  (task.description?.trim().length ?? 0) >= MIN_SPECIFIED_DESCRIPTION_LENGTH;

const matchesWontfix = (task: HubTaskProjection): boolean =>
  /\b(wontfix|won'?t\s*fix|duplicate|not a bug)\b/i.test(taskText(task));

const matchesHumanOwned = (task: HubTaskProjection): boolean => {
  const kind = String(task.metadata.kind ?? task.metadata.category ?? "")
    .trim()
    .toLowerCase();
  if (kind === "human" || kind === "hitl") {
    return true;
  }

  const executionMode = String(
    task.metadata.execution_mode ?? task.metadata.executionMode ?? "",
  )
    .trim()
    .toLowerCase();
  if (executionMode === "human" || executionMode === "hitl") {
    return true;
  }

  return /\b(hitl|human[- ]owned|requires human)\b/i.test(taskText(task));
};

const lastTriageCommentIndex = (task: HubTaskProjection): number => {
  let lastIndex = -1;
  for (const [index, comment] of task.comments.entries()) {
    if (isHubTriageComment(comment.body)) {
      lastIndex = index;
    }
  }
  return lastIndex;
};

const hasNewUserInformation = (task: HubTaskProjection): boolean => {
  const lastTriageIndex = lastTriageCommentIndex(task);
  if (lastTriageIndex < 0) {
    return task.comments.some((comment) => !isHubTriageComment(comment.body));
  }

  return task.comments
    .slice(lastTriageIndex + 1)
    .some((comment) => !isHubTriageComment(comment.body));
};

export const classifyHubTaskForTriage = (
  task: HubTaskProjection,
): HubTriageDecision => {
  if (matchesWontfix(task)) {
    return {
      outcome: "wontfix",
      summary:
        "Marked wontfix during triage because the task is not actionable.",
    };
  }

  if (!hasSufficientSpecification(task)) {
    if (task.hubStatus === "needs_info" && !hasNewUserInformation(task)) {
      return {
        outcome: "needs_info",
        summary:
          "Still waiting on reporter input before this task can move forward.",
      };
    }

    return {
      outcome: "needs_info",
      summary:
        "Needs more information before agent or human work can start safely.",
    };
  }

  if (matchesHumanOwned(task)) {
    return {
      outcome: "ready_for_human",
      summary:
        "Ready for human-owned work instead of routing it through a blocked reason.",
    };
  }

  return {
    outcome: "ready_for_agent",
    summary: "Ready for AFK agent implementation.",
  };
};

const applyHubTaskTriageOutcome = (
  cwd: string,
  taskId: string,
  task: HubTaskProjection,
  outcome: HubTriageOutcome,
  env: NodeJS.ProcessEnv,
): void => {
  const metadata: Record<string, unknown> = {
    ...task.metadata,
    hub_status: outcome,
  };

  if (outcome === "wontfix") {
    metadata.wontfix = true;
  } else {
    delete metadata.wontfix;
  }

  const args = ["update", taskId, "--set-metadata", JSON.stringify(metadata)];
  for (const label of TRIAGE_LABELS_TO_CLEAR) {
    args.push("--remove-labels", label);
  }

  if (outcome === "wontfix") {
    args.push("--status", "closed", "--add-labels", OUTCOME_LABELS.wontfix);
  } else {
    args.push("--status", "open", "--add-labels", OUTCOME_LABELS[outcome]);
  }

  runBdText(cwd, args, `tasks triage ${taskId}`, env);
};

export const triageHubTasks = (
  input: TriageHubTasksInput,
): TriageHubTasksResult => {
  const env = input.env ?? process.env;
  const classify = input.classify ?? classifyHubTaskForTriage;
  const board = loadHubTaskBoard(input.cwd, env);
  const triaged: TriageHubTaskRecord[] = [];
  const skipped: { taskId: string; reason: string }[] = [];

  for (const task of board.tasks) {
    if (!HUB_TRIAGE_SOURCE_STATUS_SET.has(task.hubStatus)) {
      skipped.push({
        taskId: task.id,
        reason: `status ${task.hubStatus} is outside triage scope`,
      });
      continue;
    }

    const decision = classify(task);
    applyHubTaskTriageOutcome(input.cwd, task.id, task, decision.outcome, env);
    appendHubTaskComment(
      input.cwd,
      task.id,
      formatHubTriageComment(decision.summary),
      env,
    );
    triaged.push({
      taskId: task.id,
      priorStatus: task.hubStatus,
      outcome: decision.outcome,
    });
  }

  return { triaged, skipped };
};
