import { execFile } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { promisify } from "node:util";

import {
  evaluateHubManagedBranchCleanup,
  findHubManagedBranchCleanupCandidate,
} from "./hubManagedBranchCleanup.js";
import {
  createHubFlowRunVerifier,
  type HubFlowMerger,
  type HubFlowVerifier,
  type HubTaskCloser,
} from "./hubBatchMerge.js";
import { TaskBoardError } from "./errors.js";
import type { HubTaskEvent } from "./hubExecution.js";
import {
  resolveArchloopUserDataDir,
  resolveGitRepoRoot,
  resolveHubProjectDir,
} from "./projectStatus.js";
import {
  completeCloseFailedRecovery,
  recoverFailedHubTask,
  releaseStaleHubTaskClaim,
} from "./hubTaskLifecycle.js";
import {
  latestPhaseCompletionEventByTask,
  routeInterruptedTaskRecovery,
  type InterruptedTaskRecoveryRoute,
} from "./hubTaskRecoveryRouter.js";
import {
  detectInterruptedHubTaskExecutions,
  type InterruptedExecutionPhase,
  type InterruptedHubTaskExecution,
} from "./hubTaskInterruptedExecutionDetector.js";
import {
  appendHubTaskComment,
  loadHubTask,
  loadHubTaskBoard,
  resolveHubTaskBranch,
  updateHubTaskStatus,
  type HubFailureReason,
  type HubTaskBoard,
  type HubTaskProjection,
  type HubTaskStatus,
} from "./taskBoard.js";
import {
  listWorktreeLeases,
  type WorktreeLeaseRecord,
} from "./worktreeLeaseStore.js";
import type {
  SectionBlock,
  SectionFooterBlock,
  SectionHeaderBlock,
  SectionKvBlock,
  SectionProseBlock,
} from "./section.js";

const execFileAsync = promisify(execFile);

export const HUB_RECOVERY_COMMENT_PREFIX =
  "> *This was generated by archLoop during task recovery.*";

/**
 * Reads every run's task event log under the Hub project dir and selects each
 * task's latest phase-completion event. Mirrors the doctor's
 * `readTaskEvents` + `latestMergeReadyEventsByTask` (the helper the PRD names
 * for event-log reading), but uses the recovery router's wider phase-completion
 * selection so a reviewer-flow `task_implementation_succeeded` (status
 * `reviewing`) is recognized too. The recovery wiring injects this so the
 * router's `latestEvent` input is resolved by the caller, keeping the router a
 * pure decision table.
 */
const readPhaseCompletionEventsByTask = (
  hubProjectDir: string,
): ReadonlyMap<string, HubTaskEvent> => {
  const runsDir = join(hubProjectDir, "runs");
  if (!existsSync(runsDir)) {
    return new Map();
  }

  const events: HubTaskEvent[] = [];
  for (const entry of readdirSync(runsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }
    const taskEventsPath = join(runsDir, entry.name, "events", "task.jsonl");
    if (!existsSync(taskEventsPath)) {
      continue;
    }
    for (const line of readFileSync(taskEventsPath, "utf8").split(/\r?\n/)) {
      if (line.trim().length === 0) {
        continue;
      }
      try {
        events.push(JSON.parse(line) as HubTaskEvent);
      } catch {
        // Skip malformed event lines; a corrupt record cannot prove a phase
        // completed, so it is ignored (the task retries from ready_for_agent).
      }
    }
  }

  return latestPhaseCompletionEventByTask(events);
};

/**
 * Resolves a task's latest phase-completion event from the run event log.
 * Injectable so tests supply events without a real Hub run dir; the default
 * scans the Hub project dir derived from `cwd` / `env`.
 */
export type ResolveLatestPhaseCompletionEvent = (
  input: Readonly<{ cwd: string; taskId: string; env?: NodeJS.ProcessEnv }>,
) => Promise<HubTaskEvent | undefined>;

const defaultResolveLatestPhaseCompletionEvent: ResolveLatestPhaseCompletionEvent =
  async ({ cwd, taskId, env }) => {
    const repoRoot = resolveGitRepoRoot(cwd);
    const hubProjectDir = resolveHubProjectDir(
      resolveArchloopUserDataDir(env ?? process.env),
      repoRoot,
    );
    return readPhaseCompletionEventsByTask(hubProjectDir).get(taskId);
  };

const COLLABORATION_STATUSES = new Set<HubTaskStatus>([
  "inbox",
  "needs_info",
  "ready_for_agent",
  "ready_for_human",
  "blocked",
  "sync_conflict",
]);

const STALE_EXECUTION_STATUSES = new Set<HubTaskStatus>([
  "implementing",
  "reviewing",
  "merging",
]);

const HUMAN_FAILURE_REASONS = new Set<HubFailureReason>([
  "merge_conflict",
  "verification_failure",
]);

export type HubTaskRecoveryOutcome =
  | "released_claim"
  | "recovered_failed"
  | "recovered_close_failed"
  | "unchanged";

export interface RecoverHubTaskInput {
  readonly cwd: string;
  readonly taskId: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly verifier?: HubFlowVerifier;
  readonly closer?: HubTaskCloser;
  readonly merger?: HubFlowMerger;
  readonly isBranchMerged?: (cwd: string, branch: string) => Promise<boolean>;
  readonly branchHasUnmergedWork?: (
    cwd: string,
    branch: string,
  ) => Promise<boolean>;
  /**
   * Resolves the task's latest phase-completion event from the run event log,
   * feeding the recovery router's `latestEvent` input. Injectable so tests
   * supply events without a real Hub run dir; defaults to scanning the Hub
   * project dir derived from `cwd` / `env`.
   */
  readonly resolveLatestPhaseCompletionEvent?: ResolveLatestPhaseCompletionEvent;
}

export interface RecoverHubTaskResult {
  readonly outcome: HubTaskRecoveryOutcome;
  readonly priorStatus: HubTaskStatus;
  readonly hubStatus: HubTaskStatus;
  readonly summary: string;
  readonly task: HubTaskProjection;
}

export const isHubRecoveryComment = (body: string | undefined): boolean =>
  (body ?? "").trimStart().startsWith(HUB_RECOVERY_COMMENT_PREFIX);

export const formatHubRecoveryComment = (summary: string): string =>
  `${HUB_RECOVERY_COMMENT_PREFIX}\n\n${summary.trim()}`;

const readFailureReason = (
  task: HubTaskProjection,
): HubFailureReason | undefined => {
  const value = task.metadata.failureReason ?? task.metadata.failure_reason;
  if (typeof value !== "string") {
    return undefined;
  }

  switch (value) {
    case "agent_failed":
    case "sandbox_failed":
    case "merge_conflict":
    case "merge_failed":
    case "verification_failure":
    case "close_failed":
    case "unknown":
      return value;
    default:
      return "unknown";
  }
};

const hasTruthyMetadata = (
  metadata: Readonly<Record<string, unknown>>,
  keys: readonly string[],
): boolean =>
  keys.some((key) => {
    const value = metadata[key];
    return (
      value !== undefined &&
      value !== null &&
      value !== false &&
      !(typeof value === "string" && value.trim().length === 0)
    );
  });

export const resolveFailedRecoveryTarget = (
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): HubTaskStatus => {
  if (hasTruthyMetadata(task.metadata, ["wontfix", "wontFix", "rejected"])) {
    return "wontfix";
  }
  if (
    hasTruthyMetadata(task.metadata, [
      "blocked_reason",
      "blockedReason",
      "blocked_reason_kind",
      "blockedReasonKind",
    ])
  ) {
    return "blocked";
  }
  if (
    task.metadata.slice_type === "HITL" ||
    task.metadata.sliceType === "HITL" ||
    task.metadata.kind === "human"
  ) {
    return "ready_for_human";
  }
  if (failureReason && HUMAN_FAILURE_REASONS.has(failureReason)) {
    return "ready_for_human";
  }
  return "ready_for_agent";
};

const appendRecoveryComment = (
  input: RecoverHubTaskInput,
  summary: string,
): void => {
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );
};

const recordRecoveryResult = (
  input: RecoverHubTaskInput,
  result: RecoverHubTaskResult,
  summary = result.summary,
): RecoverHubTaskResult => {
  appendRecoveryComment(input, summary);
  if (summary === result.summary) {
    return result;
  }

  return {
    ...result,
    summary,
  };
};

export const isBranchMergedIntoHead = async (
  cwd: string,
  branch: string,
): Promise<boolean> => {
  try {
    await execFileAsync(
      "git",
      ["merge-base", "--is-ancestor", branch, "HEAD"],
      { cwd },
    );
    return true;
  } catch {
    return false;
  }
};

export const hasBranchUnmergedWork = async (
  cwd: string,
  branch: string,
): Promise<boolean> => {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["rev-list", "--count", `HEAD..${branch}`],
      { cwd, encoding: "utf8" },
    );
    return Number(String(stdout).trim()) > 0;
  } catch {
    return false;
  }
};

const resolveTaskBranch = (task: HubTaskProjection): string =>
  task.claim?.branch ?? resolveHubTaskBranch(task.id, task.title);

const deleteGitBranch = async (cwd: string, branch: string): Promise<void> => {
  await execFileAsync("git", ["branch", "-d", branch], { cwd });
};

const defaultCloseFailedRecoveryCloser: HubTaskCloser = async (closeInput) =>
  completeCloseFailedRecovery(closeInput).task;

const recoverToTargetStatus = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  targetStatus: HubTaskStatus,
  summary: string,
): RecoverHubTaskResult => {
  const { task: updatedTask } = recoverFailedHubTask({
    cwd: input.cwd,
    taskId: input.taskId,
    targetStatus,
    metadata: task.metadata,
    env: input.env,
  });

  return {
    outcome: "recovered_failed",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  };
};

const recoverCloseFailedTask = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason,
): Promise<RecoverHubTaskResult> => {
  if (failureReason !== "close_failed") {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} expected close_failed`,
    });
  }

  const branch = resolveTaskBranch(task);
  const isBranchMerged = input.isBranchMerged ?? isBranchMergedIntoHead;
  if (!(await isBranchMerged(input.cwd, branch))) {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} cannot close task because branch ${branch} is not merged into HEAD`,
    });
  }

  const verifier =
    input.verifier ?? createHubFlowRunVerifier({ cwd: input.cwd });
  const verifyResult = await verifier({
    flowId: "recovery",
    taskId: task.id,
    title: task.title,
    branch,
    cwd: input.cwd,
    runDir: input.cwd,
  });
  if (verifyResult.outcome !== "success") {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} verification failed: ${verifyResult.message ?? "verification failed"}`,
    });
  }

  const closer = input.closer ?? defaultCloseFailedRecoveryCloser;

  const closedTask = await closer({
    cwd: input.cwd,
    taskId: task.id,
    metadata: task.metadata,
    env: input.env,
  });

  const summary = `Recovered close_failed task after confirming ${branch} is already merged, rerunning verification, and retrying local Beads close.`;
  return recordRecoveryResult(input, {
    outcome: "recovered_close_failed",
    priorStatus: task.hubStatus,
    hubStatus: closedTask.hubStatus,
    summary,
    task: closedTask,
  });
};

const attemptRecoveryCleanup = async (
  input: RecoverHubTaskInput,
  branch: string,
): Promise<string> => {
  const evaluation = await evaluateHubManagedBranchCleanup({
    cwd: input.cwd,
    env: input.env,
  });
  const candidate = findHubManagedBranchCleanupCandidate(evaluation, branch);

  if (!candidate) {
    return `Cleanup skipped for ${branch}: branch is missing.`;
  }

  if (candidate.ownership === undefined) {
    return `Cleanup skipped for ${branch}: branch has no Hub-managed ownership record.`;
  }

  if (candidate.skipReasons.length > 0) {
    return `Cleanup skipped for ${branch}: ${candidate.skipReasons
      .map((detail) => detail.message)
      .join("; ")}`;
  }

  try {
    await deleteGitBranch(input.cwd, branch);
    return `Deleted safe managed branch ${branch} after recovery.`;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return `Cleanup failed for ${branch}: ${message}`;
  }
};

const recoverGenericFailedTask = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): Promise<RecoverHubTaskResult> => {
  const branch = resolveTaskBranch(task);
  const resolveBranchHasUnmergedWork =
    input.branchHasUnmergedWork ?? hasBranchUnmergedWork;
  const branchHasWork = await resolveBranchHasUnmergedWork(input.cwd, branch);

  if (branchHasWork && task.claim !== undefined) {
    const targetStatus = "waiting_for_merge";
    const summary = `Moved failed task from failed to waiting_for_merge because ${branch} has existing unmerged work.`;
    const updatedTask = updateHubTaskStatus({
      cwd: input.cwd,
      taskId: input.taskId,
      hubStatus: targetStatus,
      metadata: { ...task.metadata },
      env: input.env,
    });
    return recordRecoveryResult(input, {
      outcome: "recovered_failed",
      priorStatus: task.hubStatus,
      hubStatus: updatedTask.hubStatus,
      summary,
      task: updatedTask,
    });
  }

  const targetStatus = resolveFailedRecoveryTarget(task, failureReason);
  const recovered = recoverToTargetStatus(
    input,
    task,
    targetStatus,
    `Moved failed task from failed to ${targetStatus} and cleared execution failure metadata.`,
  );
  const cleanupSummary = await attemptRecoveryCleanup(input, branch);
  return recordRecoveryResult(
    input,
    recovered,
    `${recovered.summary} ${cleanupSummary}`,
  );
};

const releaseStaleClaim = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): RecoverHubTaskResult => {
  const { task: updatedTask } = releaseStaleHubTaskClaim({
    cwd: input.cwd,
    taskId: input.taskId,
    hubStatus: task.hubStatus,
    metadata: task.metadata,
    env: input.env,
  });
  const summary = `Released stale claim metadata while keeping hub status ${task.hubStatus}.`;
  return recordRecoveryResult(input, {
    outcome: "released_claim",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  });
};

/**
 * Builds the recovery summary for the no-event (fresh retry) stale-execution
 * branch. The router resolves a base destination of `ready_for_agent`;
 * `resolveFailedRecoveryTarget` may then override it to `ready_for_human`
 * (human-failure reason), `wontfix`, or `blocked`. Describe the actual
 * override rather than assuming every divergence is a human-failure reason.
 */
const resolveStaleExecutionSummary = (
  route: InterruptedTaskRecoveryRoute,
  targetStatus: HubTaskStatus,
  failureReason: HubFailureReason | undefined,
): string => {
  if (targetStatus === route.targetStatus) {
    return route.reason;
  }
  if (
    targetStatus === "ready_for_human" &&
    failureReason !== undefined &&
    HUMAN_FAILURE_REASONS.has(failureReason)
  ) {
    return `${route.reason} Routed to ready_for_human because the task carries a human-failure reason (${failureReason}).`;
  }
  return `${route.reason} Routed to ${targetStatus} because the task's metadata overrides the default ready_for_agent destination.`;
};

/**
 * The pure recovery plan for a single interrupted task: the destination the
 * event-aware router + failure-reason override resolve, whether the claim is
 * preserved, and a human-readable reason. Shared by the per-task recover path
 * (`recoverStaleExecutionStatus`) and the `tasks recover --stale` batch path
 * (`recoverStaleHubTasks`) so the two surfaces never diverge on routing.
 *
 * Pure over the already-resolved `latestEvent` and `branchHasUnmergedWork` —
 * the caller resolves those (consulting the run event log and git) and the
 * router + override do the rest. No mutation.
 */
export interface StaleExecutionRecoveryPlan {
  readonly priorStatus: HubTaskStatus;
  readonly targetStatus: HubTaskStatus;
  readonly preserveClaim: boolean;
  readonly reason: string;
}

export const planStaleExecutionRecovery = (
  task: HubTaskProjection,
  latestEvent: HubTaskEvent | undefined,
  branchHasUnmergedWork: boolean,
): StaleExecutionRecoveryPlan => {
  const route = routeInterruptedTaskRecovery({
    hubStatus: task.hubStatus,
    latestEvent,
    branchHasUnmergedWork,
  });

  if (route.preserveClaim) {
    return {
      priorStatus: task.hubStatus,
      targetStatus: route.targetStatus,
      preserveClaim: true,
      reason: route.reason,
    };
  }

  const failureReason = readFailureReason(task);
  const targetStatus = resolveFailedRecoveryTarget(task, failureReason);
  return {
    priorStatus: task.hubStatus,
    targetStatus,
    preserveClaim: false,
    reason: resolveStaleExecutionSummary(route, targetStatus, failureReason),
  };
};

const recoverStaleExecutionStatus = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): Promise<RecoverHubTaskResult> => {
  const resolveLatestPhaseCompletionEvent =
    input.resolveLatestPhaseCompletionEvent ??
    defaultResolveLatestPhaseCompletionEvent;
  const latestEvent = await resolveLatestPhaseCompletionEvent({
    cwd: input.cwd,
    taskId: task.id,
    env: input.env,
  });

  // The router only consults branchHasUnmergedWork on the no-event retry
  // path, so skip the git call entirely when a finished-phase event is
  // present (it would not change the route).
  const branch = resolveTaskBranch(task);
  const resolveBranchHasUnmergedWork =
    input.branchHasUnmergedWork ?? hasBranchUnmergedWork;
  const branchHasUnmergedWork =
    latestEvent === undefined
      ? await resolveBranchHasUnmergedWork(input.cwd, branch)
      : false;

  const plan = planStaleExecutionRecovery(
    task,
    latestEvent,
    branchHasUnmergedWork,
  );

  if (plan.preserveClaim) {
    // A finished phase is preserved: the task resumes at the phase the success
    // event was advancing it to, and its claim metadata is kept so the
    // resumed-batch merge path (which keys off claim.runId / claim.batchId)
    // can find it. reviewing and waiting_for_merge are claim-preserving
    // statuses, so updateHubTaskStatus keeps the existing claim (it does not
    // go through recoverFailedHubTask, which strips the claim).
    const updatedTask = updateHubTaskStatus({
      cwd: input.cwd,
      taskId: input.taskId,
      hubStatus: plan.targetStatus,
      metadata: { ...task.metadata },
      env: input.env,
    });
    return recordRecoveryResult(input, {
      outcome: "recovered_failed",
      priorStatus: task.hubStatus,
      hubStatus: updatedTask.hubStatus,
      summary: plan.reason,
      task: updatedTask,
    });
  }

  // No phase-completion signal: implementation was interrupted before any
  // phase finished, so the task retries from ready_for_agent. The real
  // failureReason (not undefined) is passed to resolveFailedRecoveryTarget so
  // the human-failure-reason override can fire (story 17): a stale-execution
  // task whose metadata carries a human-failure reason routes to
  // ready_for_human rather than ready_for_agent. The claim is stripped
  // (ready_for_agent is not claim-preserving).
  const result = recoverToTargetStatus(
    input,
    task,
    plan.targetStatus,
    plan.reason,
  );
  return recordRecoveryResult(input, result);
};

export const recoverHubTask = async (
  input: RecoverHubTaskInput,
): Promise<RecoverHubTaskResult> => {
  const task = loadHubTask(input.cwd, input.taskId, input.env);
  const failureReason = readFailureReason(task);

  if (task.hubStatus === "failed") {
    if (failureReason === "close_failed") {
      return recoverCloseFailedTask(input, task, failureReason);
    }
    return recoverGenericFailedTask(input, task, failureReason);
  }

  if (STALE_EXECUTION_STATUSES.has(task.hubStatus)) {
    return recoverStaleExecutionStatus(input, task);
  }

  if (
    task.claimState === "stale" &&
    COLLABORATION_STATUSES.has(task.hubStatus)
  ) {
    return releaseStaleClaim(input, task);
  }

  throw new TaskBoardError({
    message: `archloop tasks recover ${input.taskId} found no recoverable failed or stale execution state (status: ${task.hubStatus})`,
  });
};

// ---------------------------------------------------------------------------
// tasks recover --stale — batch recovery with dry-run preview (arch-6y9)
// ---------------------------------------------------------------------------

/**
 * One task's planned (or, after `yes`, applied) stale-execution recovery in a
 * `tasks recover --stale` batch. The routing is identical to the per-task path
 * (`planStaleExecutionRecovery`), so the preview the user reviews matches what
 * `recoverHubTask` will do when applied.
 */
export interface StaleHubTaskRecoveryEntry {
  readonly taskId: string;
  readonly title: string;
  /** The execution phase the task was stuck in (`implementing`/`reviewing`/`merging`). */
  readonly phase: InterruptedExecutionPhase;
  readonly priorStatus: HubTaskStatus;
  readonly targetStatus: HubTaskStatus;
  readonly preserveClaim: boolean;
  readonly reason: string;
  /** Present after the recovery is applied; `undefined` in a dry-run preview. */
  readonly outcome?: HubTaskRecoveryOutcome;
}

export interface RecoverStaleHubTasksInput {
  readonly cwd: string;
  readonly env?: NodeJS.ProcessEnv;
  /**
   * Apply the recovery after previewing. When false (default) the function is
   * read-only: it builds and returns the plan without mutating task state.
   */
  readonly yes?: boolean;
  /** Injectable board loader (defaults to `loadHubTaskBoard`). */
  readonly loadBoard?: (cwd: string, env: NodeJS.ProcessEnv) => HubTaskBoard;
  /** Injectable worktree-lease loader (defaults to `listWorktreeLeases`). */
  readonly listLeases?: (repoRoot: string) => readonly WorktreeLeaseRecord[];
  /**
   * Injectable per-task recovery. Defaults to `recoverHubTask` so the batch
   * path shares the single source of truth for routing + mutation. Only called
   * when `yes` is set; the dry-run preview is computed from
   * `planStaleExecutionRecovery` without invoking this.
   */
  readonly recoverTask?: (
    input: RecoverHubTaskInput,
  ) => Promise<RecoverHubTaskResult>;
  readonly resolveLatestPhaseCompletionEvent?: ResolveLatestPhaseCompletionEvent;
  readonly branchHasUnmergedWork?: (
    cwd: string,
    branch: string,
  ) => Promise<boolean>;
}

export interface RecoverStaleHubTasksResult {
  /** Whether the recovery was applied (true only when `yes` was passed). */
  readonly applied: boolean;
  readonly entries: readonly StaleHubTaskRecoveryEntry[];
}

/**
 * Recover every interrupted-execution task on the board in one command
 * (`tasks recover --stale`). Loads the board, worktree leases, and run event
 * log; runs the shared interrupted-execution detector across the board; and
 * routes each interrupted task through the event-aware recovery router.
 *
 * By default (`yes` unset) this is a read-only dry run: it returns the planned
 * routing per task so the user can verify nothing will be re-implemented
 * unnecessarily (story 10). The recovery is applied only when `yes` is set
 * (story 11), by delegating to `recoverHubTask` per task so the batch path and
 * the per-task path can never diverge on routing or mutation.
 */
export const recoverStaleHubTasks = async (
  input: RecoverStaleHubTasksInput,
): Promise<RecoverStaleHubTasksResult> => {
  const cwd = input.cwd;
  const loadBoard = input.loadBoard ?? loadHubTaskBoard;
  const listLeases = input.listLeases ?? listWorktreeLeases;
  const resolveLatestPhaseCompletionEvent =
    input.resolveLatestPhaseCompletionEvent ??
    defaultResolveLatestPhaseCompletionEvent;
  const resolveBranchHasUnmergedWork =
    input.branchHasUnmergedWork ?? hasBranchUnmergedWork;

  const board = loadBoard(cwd, input.env ?? process.env);
  const leases = listLeases(cwd);
  const interrupted = detectInterruptedHubTaskExecutions(board.tasks, leases);

  // Build the dry-run plan first (read-only), so even when applying we return
  // the same routing the user reviewed. The event + branch lookups are needed
  // to compute the route; reuse the per-task resolver conventions. `cwd` is the
  // repo root in the CLI path (resolved before this function is called); the
  // injected-fake tests bypass these defaults with a non-git cwd.
  const plans = await Promise.all(
    interrupted.map(async (entry: InterruptedHubTaskExecution) => {
      const latestEvent = await resolveLatestPhaseCompletionEvent({
        cwd,
        taskId: entry.taskId,
        env: input.env,
      });
      const branch = resolveTaskBranch(entry.task);
      const branchHasUnmergedWork =
        latestEvent === undefined
          ? await resolveBranchHasUnmergedWork(cwd, branch)
          : false;
      const plan = planStaleExecutionRecovery(
        entry.task,
        latestEvent,
        branchHasUnmergedWork,
      );
      return {
        entry,
        plan,
        latestEvent,
        branchHasUnmergedWork,
      };
    }),
  );

  const entries: StaleHubTaskRecoveryEntry[] = plans.map(({ entry, plan }) => ({
    taskId: entry.taskId,
    title: entry.task.title,
    phase: entry.phase,
    priorStatus: plan.priorStatus,
    targetStatus: plan.targetStatus,
    preserveClaim: plan.preserveClaim,
    reason: plan.reason,
  }));

  if (!input.yes || entries.length === 0) {
    return { applied: false, entries };
  }

  // Apply: delegate to recoverHubTask per task so the batch path reuses the
  // single mutation source (routing, claim strip/preserve, recovery comment).
  const recoverTask = input.recoverTask ?? recoverHubTask;
  const results = await Promise.all(
    plans.map(async ({ entry }) => {
      const result = await recoverTask({
        cwd,
        taskId: entry.taskId,
        env: input.env,
        resolveLatestPhaseCompletionEvent,
        branchHasUnmergedWork: resolveBranchHasUnmergedWork,
      });
      return { taskId: entry.taskId, result };
    }),
  );

  const outcomeByTask = new Map(
    results.map(({ taskId, result }) => [taskId, result.outcome]),
  );
  return {
    applied: true,
    entries: entries.map((entry) => ({
      ...entry,
      outcome: outcomeByTask.get(entry.taskId),
    })),
  };
};

// ---------------------------------------------------------------------------
// tasks recover summary model (Variant C section primitive)
// ---------------------------------------------------------------------------

const RECOVER_KV_GUTTER = 14;

export interface HubTaskRecoverSummaryModel {
  readonly header: SectionHeaderBlock;
  readonly identity: SectionKvBlock;
  readonly summary: SectionProseBlock;
  readonly footer: SectionFooterBlock;
}

export interface BuildHubTaskRecoverSummaryModelInput {
  readonly taskId: string;
  readonly result: RecoverHubTaskResult;
}

export const buildHubTaskRecoverSummaryModel = (
  input: BuildHubTaskRecoverSummaryModelInput,
): HubTaskRecoverSummaryModel => {
  const { taskId, result } = input;
  const rows: SectionKvBlock["rows"][number][] = [
    { key: "outcome", value: result.outcome },
    { key: "prior status", value: result.priorStatus },
    { key: "hub status", value: result.hubStatus },
  ];

  return {
    header: {
      kind: "header",
      title: "archLoop",
      subtitle: `tasks · recover · ${taskId}`,
      right: result.outcome,
    },
    identity: {
      kind: "kv",
      gutter: RECOVER_KV_GUTTER,
      rows,
    },
    summary: {
      kind: "prose",
      title: "summary",
      body: result.summary,
    },
    footer: {
      kind: "footer",
      label: "next",
      command: `archloop tasks show ${taskId}`,
    },
  };
};

export const hubTaskRecoverSummaryModelToBlocks = (
  model: HubTaskRecoverSummaryModel,
): readonly SectionBlock[] => [
  model.header,
  model.identity,
  model.summary,
  model.footer,
];

// ---------------------------------------------------------------------------
// tasks recover --stale preview/applied formatting
// ---------------------------------------------------------------------------

const claimLabel = (entry: StaleHubTaskRecoveryEntry): string =>
  entry.preserveClaim
    ? "preserve claim"
    : "release claim";

/**
 * Formats a `tasks recover --stale` result as plain lines for the CLI. The
 * dry-run preview lists the planned routing per task so the user can verify
 * nothing will be re-implemented unnecessarily; the applied view mirrors it
 * with the recorded outcome. Mirrors the `formatHubTaskStateRepairLines`
 * shape so the two batch surfaces read consistently.
 */
export const formatStaleHubTaskRecoveryLines = (
  result: RecoverStaleHubTasksResult,
): readonly string[] => {
  const lines: string[] = ["Stale execution recovery"];
  if (result.entries.length === 0) {
    lines.push("No interrupted tasks found on the board.");
    return lines;
  }

  lines.push(
    result.applied ? `Applied recovery for ${result.entries.length} task(s):` : `Planned recovery for ${result.entries.length} interrupted task(s):`,
  );
  for (const entry of result.entries) {
    const outcome =
      result.applied && entry.outcome !== undefined
        ? ` [${entry.outcome}]`
        : "";
    lines.push(
      `  ${entry.taskId}: ${entry.priorStatus} -> ${entry.targetStatus} (${claimLabel(entry)})${outcome}`,
    );
    lines.push(`    ${entry.reason}`);
  }
  if (!result.applied) {
    lines.push("Re-run with --yes to apply this batch recovery.");
  }
  return lines;
};
