import { execFile } from "node:child_process";
import { promisify } from "node:util";

import {
  evaluateHubManagedBranchCleanup,
  findHubManagedBranchCleanupCandidate,
} from "./hubManagedBranchCleanup.js";
import {
  createHubFlowRunVerifier,
  type HubFlowMerger,
  type HubFlowVerifier,
  type HubTaskCloser,
} from "./hubBatchMerge.js";
import { TaskBoardError } from "./errors.js";
import {
  completeCloseFailedRecovery,
  recoverFailedHubTask,
  releaseStaleHubTaskClaim,
} from "./hubTaskLifecycle.js";
import {
  appendHubTaskComment,
  loadHubTask,
  resolveHubTaskBranch,
  updateHubTaskStatus,
  type HubFailureReason,
  type HubTaskProjection,
  type HubTaskStatus,
} from "./taskBoard.js";
import type {
  SectionBlock,
  SectionFooterBlock,
  SectionHeaderBlock,
  SectionKvBlock,
  SectionProseBlock,
} from "./section.js";

const execFileAsync = promisify(execFile);

export const HUB_RECOVERY_COMMENT_PREFIX =
  "> *This was generated by archLoop during task recovery.*";

const COLLABORATION_STATUSES = new Set<HubTaskStatus>([
  "inbox",
  "needs_info",
  "ready_for_agent",
  "ready_for_human",
  "blocked",
  "sync_conflict",
]);

const STALE_EXECUTION_STATUSES = new Set<HubTaskStatus>([
  "implementing",
  "reviewing",
  "merging",
]);

const HUMAN_FAILURE_REASONS = new Set<HubFailureReason>([
  "merge_conflict",
  "verification_failure",
]);

export type HubTaskRecoveryOutcome =
  | "released_claim"
  | "recovered_failed"
  | "recovered_close_failed"
  | "unchanged";

export interface RecoverHubTaskInput {
  readonly cwd: string;
  readonly taskId: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly verifier?: HubFlowVerifier;
  readonly closer?: HubTaskCloser;
  readonly merger?: HubFlowMerger;
  readonly isBranchMerged?: (cwd: string, branch: string) => Promise<boolean>;
  readonly branchHasUnmergedWork?: (
    cwd: string,
    branch: string,
  ) => Promise<boolean>;
}

export interface RecoverHubTaskResult {
  readonly outcome: HubTaskRecoveryOutcome;
  readonly priorStatus: HubTaskStatus;
  readonly hubStatus: HubTaskStatus;
  readonly summary: string;
  readonly task: HubTaskProjection;
}

export const isHubRecoveryComment = (body: string | undefined): boolean =>
  (body ?? "").trimStart().startsWith(HUB_RECOVERY_COMMENT_PREFIX);

export const formatHubRecoveryComment = (summary: string): string =>
  `${HUB_RECOVERY_COMMENT_PREFIX}\n\n${summary.trim()}`;

const readFailureReason = (
  task: HubTaskProjection,
): HubFailureReason | undefined => {
  const value = task.metadata.failureReason ?? task.metadata.failure_reason;
  if (typeof value !== "string") {
    return undefined;
  }

  switch (value) {
    case "agent_failed":
    case "sandbox_failed":
    case "merge_conflict":
    case "merge_failed":
    case "verification_failure":
    case "close_failed":
    case "unknown":
      return value;
    default:
      return "unknown";
  }
};

const hasTruthyMetadata = (
  metadata: Readonly<Record<string, unknown>>,
  keys: readonly string[],
): boolean =>
  keys.some((key) => {
    const value = metadata[key];
    return (
      value !== undefined &&
      value !== null &&
      value !== false &&
      !(typeof value === "string" && value.trim().length === 0)
    );
  });

export const resolveFailedRecoveryTarget = (
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): HubTaskStatus => {
  if (hasTruthyMetadata(task.metadata, ["wontfix", "wontFix", "rejected"])) {
    return "wontfix";
  }
  if (
    hasTruthyMetadata(task.metadata, [
      "blocked_reason",
      "blockedReason",
      "blocked_reason_kind",
      "blockedReasonKind",
    ])
  ) {
    return "blocked";
  }
  if (
    task.metadata.slice_type === "HITL" ||
    task.metadata.sliceType === "HITL" ||
    task.metadata.kind === "human"
  ) {
    return "ready_for_human";
  }
  if (failureReason && HUMAN_FAILURE_REASONS.has(failureReason)) {
    return "ready_for_human";
  }
  return "ready_for_agent";
};

const appendRecoveryComment = (
  input: RecoverHubTaskInput,
  summary: string,
): void => {
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );
};

const recordRecoveryResult = (
  input: RecoverHubTaskInput,
  result: RecoverHubTaskResult,
  summary = result.summary,
): RecoverHubTaskResult => {
  appendRecoveryComment(input, summary);
  if (summary === result.summary) {
    return result;
  }

  return {
    ...result,
    summary,
  };
};

export const isBranchMergedIntoHead = async (
  cwd: string,
  branch: string,
): Promise<boolean> => {
  try {
    await execFileAsync(
      "git",
      ["merge-base", "--is-ancestor", branch, "HEAD"],
      { cwd },
    );
    return true;
  } catch {
    return false;
  }
};

export const hasBranchUnmergedWork = async (
  cwd: string,
  branch: string,
): Promise<boolean> => {
  try {
    const { stdout } = await execFileAsync(
      "git",
      ["rev-list", "--count", `HEAD..${branch}`],
      { cwd, encoding: "utf8" },
    );
    return Number(String(stdout).trim()) > 0;
  } catch {
    return false;
  }
};

const resolveTaskBranch = (task: HubTaskProjection): string =>
  task.claim?.branch ?? resolveHubTaskBranch(task.id, task.title);

const deleteGitBranch = async (cwd: string, branch: string): Promise<void> => {
  await execFileAsync("git", ["branch", "-d", branch], { cwd });
};

const defaultCloseFailedRecoveryCloser: HubTaskCloser = async (closeInput) =>
  completeCloseFailedRecovery(closeInput).task;

const recoverToTargetStatus = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  targetStatus: HubTaskStatus,
  summary: string,
): RecoverHubTaskResult => {
  const { task: updatedTask } = recoverFailedHubTask({
    cwd: input.cwd,
    taskId: input.taskId,
    targetStatus,
    metadata: task.metadata,
    env: input.env,
  });

  return {
    outcome: "recovered_failed",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  };
};

const recoverCloseFailedTask = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason,
): Promise<RecoverHubTaskResult> => {
  if (failureReason !== "close_failed") {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} expected close_failed`,
    });
  }

  const branch = resolveTaskBranch(task);
  const isBranchMerged = input.isBranchMerged ?? isBranchMergedIntoHead;
  if (!(await isBranchMerged(input.cwd, branch))) {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} cannot close task because branch ${branch} is not merged into HEAD`,
    });
  }

  const verifier =
    input.verifier ?? createHubFlowRunVerifier({ cwd: input.cwd });
  const verifyResult = await verifier({
    flowId: "recovery",
    taskId: task.id,
    title: task.title,
    branch,
    cwd: input.cwd,
    runDir: input.cwd,
  });
  if (verifyResult.outcome !== "success") {
    throw new TaskBoardError({
      message: `archloop tasks recover ${input.taskId} verification failed: ${verifyResult.message ?? "verification failed"}`,
    });
  }

  const closer = input.closer ?? defaultCloseFailedRecoveryCloser;

  const closedTask = await closer({
    cwd: input.cwd,
    taskId: task.id,
    metadata: task.metadata,
    env: input.env,
  });

  const summary = `Recovered close_failed task after confirming ${branch} is already merged, rerunning verification, and retrying local Beads close.`;
  return recordRecoveryResult(input, {
    outcome: "recovered_close_failed",
    priorStatus: task.hubStatus,
    hubStatus: closedTask.hubStatus,
    summary,
    task: closedTask,
  });
};

const attemptRecoveryCleanup = async (
  input: RecoverHubTaskInput,
  branch: string,
): Promise<string> => {
  const evaluation = await evaluateHubManagedBranchCleanup({
    cwd: input.cwd,
    env: input.env,
  });
  const candidate = findHubManagedBranchCleanupCandidate(evaluation, branch);

  if (!candidate) {
    return `Cleanup skipped for ${branch}: branch is missing.`;
  }

  if (candidate.ownership === undefined) {
    return `Cleanup skipped for ${branch}: branch has no Hub-managed ownership record.`;
  }

  if (candidate.skipReasons.length > 0) {
    return `Cleanup skipped for ${branch}: ${candidate.skipReasons
      .map((detail) => detail.message)
      .join("; ")}`;
  }

  try {
    await deleteGitBranch(input.cwd, branch);
    return `Deleted safe managed branch ${branch} after recovery.`;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return `Cleanup failed for ${branch}: ${message}`;
  }
};

const recoverGenericFailedTask = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): Promise<RecoverHubTaskResult> => {
  const branch = resolveTaskBranch(task);
  const branchHasWork = await (
    input.branchHasUnmergedWork ?? hasBranchUnmergedWork
  )(input.cwd, branch);

  if (branchHasWork && task.claim !== undefined) {
    const targetStatus = "waiting_for_merge";
    const summary = `Moved failed task from failed to waiting_for_merge because ${branch} has existing unmerged work.`;
    const updatedTask = updateHubTaskStatus({
      cwd: input.cwd,
      taskId: input.taskId,
      hubStatus: targetStatus,
      metadata: { ...task.metadata },
      env: input.env,
    });
    return recordRecoveryResult(input, {
      outcome: "recovered_failed",
      priorStatus: task.hubStatus,
      hubStatus: updatedTask.hubStatus,
      summary,
      task: updatedTask,
    });
  }

  const targetStatus = resolveFailedRecoveryTarget(task, failureReason);
  const recovered = recoverToTargetStatus(
    input,
    task,
    targetStatus,
    `Moved failed task from failed to ${targetStatus} and cleared execution failure metadata.`,
  );
  const cleanupSummary = await attemptRecoveryCleanup(input, branch);
  return recordRecoveryResult(
    input,
    recovered,
    `${recovered.summary} ${cleanupSummary}`,
  );
};

const releaseStaleClaim = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): RecoverHubTaskResult => {
  const { task: updatedTask } = releaseStaleHubTaskClaim({
    cwd: input.cwd,
    taskId: input.taskId,
    hubStatus: task.hubStatus,
    metadata: task.metadata,
    env: input.env,
  });
  const summary = `Released stale claim metadata while keeping hub status ${task.hubStatus}.`;
  return recordRecoveryResult(input, {
    outcome: "released_claim",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  });
};

const recoverStaleExecutionStatus = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): RecoverHubTaskResult => {
  const targetStatus = resolveFailedRecoveryTarget(task, undefined);
  const result = recoverToTargetStatus(
    input,
    task,
    targetStatus,
    `Reset stale execution status ${task.hubStatus} to ${targetStatus} and released claim metadata.`,
  );
  return recordRecoveryResult(input, result);
};

export const recoverHubTask = async (
  input: RecoverHubTaskInput,
): Promise<RecoverHubTaskResult> => {
  const task = loadHubTask(input.cwd, input.taskId, input.env);
  const failureReason = readFailureReason(task);

  if (task.hubStatus === "failed") {
    if (failureReason === "close_failed") {
      return recoverCloseFailedTask(input, task, failureReason);
    }
    return recoverGenericFailedTask(input, task, failureReason);
  }

  if (STALE_EXECUTION_STATUSES.has(task.hubStatus)) {
    return recoverStaleExecutionStatus(input, task);
  }

  if (
    task.claimState === "stale" &&
    COLLABORATION_STATUSES.has(task.hubStatus)
  ) {
    return releaseStaleClaim(input, task);
  }

  throw new TaskBoardError({
    message: `archloop tasks recover ${input.taskId} found no recoverable failed or stale execution state (status: ${task.hubStatus})`,
  });
};

// ---------------------------------------------------------------------------
// tasks recover summary model (Variant C section primitive)
// ---------------------------------------------------------------------------

const RECOVER_KV_GUTTER = 14;

export interface HubTaskRecoverSummaryModel {
  readonly header: SectionHeaderBlock;
  readonly identity: SectionKvBlock;
  readonly summary: SectionProseBlock;
  readonly footer: SectionFooterBlock;
}

export interface BuildHubTaskRecoverSummaryModelInput {
  readonly taskId: string;
  readonly result: RecoverHubTaskResult;
}

export const buildHubTaskRecoverSummaryModel = (
  input: BuildHubTaskRecoverSummaryModelInput,
): HubTaskRecoverSummaryModel => {
  const { taskId, result } = input;
  const rows: SectionKvBlock["rows"][number][] = [
    { key: "outcome", value: result.outcome },
    { key: "prior status", value: result.priorStatus },
    { key: "hub status", value: result.hubStatus },
  ];

  return {
    header: {
      kind: "header",
      title: "archLoop",
      subtitle: `tasks · recover · ${taskId}`,
      right: result.outcome,
    },
    identity: {
      kind: "kv",
      gutter: RECOVER_KV_GUTTER,
      rows,
    },
    summary: {
      kind: "prose",
      title: "summary",
      body: result.summary,
    },
    footer: {
      kind: "footer",
      label: "next",
      command: `archloop tasks show ${taskId}`,
    },
  };
};

export const hubTaskRecoverSummaryModelToBlocks = (
  model: HubTaskRecoverSummaryModel,
): readonly SectionBlock[] => [
  model.header,
  model.identity,
  model.summary,
  model.footer,
];
