import { execFile } from "node:child_process";
import { promisify } from "node:util";

import {
  createHubFlowRunVerifier,
  type HubFlowMerger,
  type HubFlowVerifier,
  type HubTaskCloser,
} from "./hubBatchMerge.js";
import { TaskBoardError } from "./errors.js";
import {
  appendHubTaskComment,
  closeHubTask,
  loadHubTask,
  resolveHubTaskBranch,
  updateHubTaskStatus,
  type HubFailureReason,
  type HubTaskProjection,
  type HubTaskStatus,
} from "./taskBoard.js";

const execFileAsync = promisify(execFile);

export const HUB_RECOVERY_COMMENT_PREFIX =
  "> *This was generated by Sandcastle during task recovery.*";

const COLLABORATION_STATUSES = new Set<HubTaskStatus>([
  "inbox",
  "needs_info",
  "ready_for_agent",
  "ready_for_human",
  "blocked",
  "sync_conflict",
]);

const STALE_EXECUTION_STATUSES = new Set<HubTaskStatus>([
  "implementing",
  "reviewing",
  "merging",
]);

const HUMAN_FAILURE_REASONS = new Set<HubFailureReason>([
  "merge_conflict",
  "verification_failure",
]);

export type HubTaskRecoveryOutcome =
  | "released_claim"
  | "recovered_failed"
  | "recovered_close_failed"
  | "unchanged";

export interface RecoverHubTaskInput {
  readonly cwd: string;
  readonly taskId: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly verifier?: HubFlowVerifier;
  readonly closer?: HubTaskCloser;
  readonly merger?: HubFlowMerger;
  readonly isBranchMerged?: (cwd: string, branch: string) => Promise<boolean>;
}

export interface RecoverHubTaskResult {
  readonly outcome: HubTaskRecoveryOutcome;
  readonly priorStatus: HubTaskStatus;
  readonly hubStatus: HubTaskStatus;
  readonly summary: string;
  readonly task: HubTaskProjection;
}

export const isHubRecoveryComment = (body: string | undefined): boolean =>
  (body ?? "").trimStart().startsWith(HUB_RECOVERY_COMMENT_PREFIX);

export const formatHubRecoveryComment = (summary: string): string =>
  `${HUB_RECOVERY_COMMENT_PREFIX}\n\n${summary.trim()}`;

const readFailureReason = (
  task: HubTaskProjection,
): HubFailureReason | undefined => {
  const value = task.metadata.failureReason ?? task.metadata.failure_reason;
  if (typeof value !== "string") {
    return undefined;
  }

  switch (value) {
    case "agent_failed":
    case "sandbox_failed":
    case "merge_conflict":
    case "verification_failure":
    case "close_failed":
    case "unknown":
      return value;
    default:
      return "unknown";
  }
};

const hasTruthyMetadata = (
  metadata: Readonly<Record<string, unknown>>,
  keys: readonly string[],
): boolean =>
  keys.some((key) => {
    const value = metadata[key];
    return (
      value !== undefined &&
      value !== null &&
      value !== false &&
      !(typeof value === "string" && value.trim().length === 0)
    );
  });

export const resolveFailedRecoveryTarget = (
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): HubTaskStatus => {
  if (hasTruthyMetadata(task.metadata, ["wontfix", "wontFix", "rejected"])) {
    return "wontfix";
  }
  if (
    hasTruthyMetadata(task.metadata, [
      "blocked_reason",
      "blockedReason",
      "blocked_reason_kind",
      "blockedReasonKind",
    ])
  ) {
    return "blocked";
  }
  if (
    task.metadata.slice_type === "HITL" ||
    task.metadata.sliceType === "HITL" ||
    task.metadata.kind === "human"
  ) {
    return "ready_for_human";
  }
  if (failureReason && HUMAN_FAILURE_REASONS.has(failureReason)) {
    return "ready_for_human";
  }
  return "ready_for_agent";
};

const releaseClaimMetadata = (
  metadata: Readonly<Record<string, unknown>>,
): Record<string, unknown> => {
  const next = { ...metadata };
  delete next.claim;
  return next;
};

export const isBranchMergedIntoHead = async (
  cwd: string,
  branch: string,
): Promise<boolean> => {
  try {
    await execFileAsync(
      "git",
      ["merge-base", "--is-ancestor", branch, "HEAD"],
      { cwd },
    );
    return true;
  } catch {
    return false;
  }
};

const resolveTaskBranch = (task: HubTaskProjection): string =>
  task.claim?.branch ?? resolveHubTaskBranch(task.id, task.title);

const recoverCloseFailedTask = async (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason,
): Promise<RecoverHubTaskResult> => {
  if (failureReason !== "close_failed") {
    throw new TaskBoardError({
      message: `sandcastle tasks recover ${input.taskId} expected close_failed`,
    });
  }

  const branch = resolveTaskBranch(task);
  const isBranchMerged = input.isBranchMerged ?? isBranchMergedIntoHead;
  if (!(await isBranchMerged(input.cwd, branch))) {
    throw new TaskBoardError({
      message: `sandcastle tasks recover ${input.taskId} cannot close task because branch ${branch} is not merged into HEAD`,
    });
  }

  const verifier =
    input.verifier ?? createHubFlowRunVerifier({ cwd: input.cwd });
  const verifyResult = await verifier({
    flowId: "recovery",
    taskId: task.id,
    title: task.title,
    branch,
    cwd: input.cwd,
    runDir: input.cwd,
  });
  if (verifyResult.outcome !== "success") {
    throw new TaskBoardError({
      message: `sandcastle tasks recover ${input.taskId} verification failed: ${verifyResult.message ?? "verification failed"}`,
    });
  }

  const closer =
    input.closer ??
    (async (closeInput) =>
      closeHubTask({
        cwd: closeInput.cwd,
        taskId: closeInput.taskId,
        metadata: closeInput.metadata,
        env: closeInput.env,
      }));

  const closedTask = await closer({
    cwd: input.cwd,
    taskId: task.id,
    metadata: releaseClaimMetadata(task.metadata),
    env: input.env,
  });

  const summary = `Recovered close_failed task after confirming ${branch} is already merged, rerunning verification, and retrying local Beads close.`;
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );

  return {
    outcome: "recovered_close_failed",
    priorStatus: task.hubStatus,
    hubStatus: closedTask.hubStatus,
    summary,
    task: closedTask,
  };
};

const recoverGenericFailedTask = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
  failureReason: HubFailureReason | undefined,
): RecoverHubTaskResult => {
  const targetStatus = resolveFailedRecoveryTarget(task, failureReason);
  const metadata = releaseClaimMetadata(task.metadata);
  const updatedTask = updateHubTaskStatus({
    cwd: input.cwd,
    taskId: input.taskId,
    hubStatus: targetStatus,
    metadata,
    replaceMetadata: true,
    env: input.env,
  });

  const summary = `Moved failed task from failed to ${targetStatus} and cleared execution failure metadata.`;
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );

  return {
    outcome: "recovered_failed",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  };
};

const releaseStaleClaim = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): RecoverHubTaskResult => {
  const metadata = releaseClaimMetadata(task.metadata);
  updateHubTaskStatus({
    cwd: input.cwd,
    taskId: input.taskId,
    hubStatus: task.hubStatus,
    metadata,
    replaceMetadata: true,
    env: input.env,
  });
  const updatedTask = loadHubTask(input.cwd, input.taskId, input.env);
  const summary = `Released stale claim metadata while keeping hub status ${task.hubStatus}.`;
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );

  return {
    outcome: "released_claim",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  };
};

const recoverStaleExecutionStatus = (
  input: RecoverHubTaskInput,
  task: HubTaskProjection,
): RecoverHubTaskResult => {
  const targetStatus = resolveFailedRecoveryTarget(task, undefined);
  const metadata = releaseClaimMetadata(task.metadata);
  const updatedTask = updateHubTaskStatus({
    cwd: input.cwd,
    taskId: input.taskId,
    hubStatus: targetStatus,
    metadata,
    replaceMetadata: true,
    env: input.env,
  });
  const summary = `Reset stale execution status ${task.hubStatus} to ${targetStatus} and released claim metadata.`;
  appendHubTaskComment(
    input.cwd,
    input.taskId,
    formatHubRecoveryComment(summary),
    input.env,
  );

  return {
    outcome: "recovered_failed",
    priorStatus: task.hubStatus,
    hubStatus: updatedTask.hubStatus,
    summary,
    task: updatedTask,
  };
};

export const recoverHubTask = async (
  input: RecoverHubTaskInput,
): Promise<RecoverHubTaskResult> => {
  const task = loadHubTask(input.cwd, input.taskId, input.env);
  const failureReason = readFailureReason(task);

  if (task.hubStatus === "failed") {
    if (failureReason === "close_failed") {
      return recoverCloseFailedTask(input, task, failureReason);
    }
    return recoverGenericFailedTask(input, task, failureReason);
  }

  if (STALE_EXECUTION_STATUSES.has(task.hubStatus)) {
    return recoverStaleExecutionStatus(input, task);
  }

  if (
    task.claimState === "stale" &&
    COLLABORATION_STATUSES.has(task.hubStatus)
  ) {
    return releaseStaleClaim(input, task);
  }

  throw new TaskBoardError({
    message: `sandcastle tasks recover ${input.taskId} found no recoverable failed or stale execution state (status: ${task.hubStatus})`,
  });
};
